"""add login table

Revision ID: 8dff73715151
Revises: cb0ad0dbfb4b
Create Date: 2025-05-13 14:29:24.017040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dff73715151'
down_revision: Union[str, None] = 'cb0ad0dbfb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint('students_email_key', 'students', type_='unique')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('students_email_key', 'students', ['email'])
    op.drop_table('login')
    # ### end Alembic commands ###
